function L = Lfun33_(Vzero,q)
%LFUN33_
%    L = LFUN33_(VZERO,Q)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    24-Nov-2020 16:27:09

L = [Vzero+q;Vzero;Vzero;Vzero;Vzero;Vzero;Vzero;Vzero;Vzero;Vzero];
