function L = Lfun21_(Vzero,dme,dmz,dpz,q,qeeeme,qeeme,qeme,qemz,qepz,qezeme,qezme,qezmz,qezpz,qmz,qpz,qzmz,qzpz,qzzmz,qzzpz)
%LFUN21_
%    L = LFUN21_(VZERO,DME,DMZ,DPZ,Q,QEEEME,QEEME,QEME,QEMZ,QEPZ,QEZEME,QEZME,QEZMZ,QEZPZ,QMZ,QPZ,QZMZ,QZPZ,QZZMZ,QZZPZ)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    24-Nov-2020 14:21:16

L = [Vzero+q;Vzero+qeme+dme.*qeeme;Vzero+qeeme+dme.*qeeeme;Vzero+qeeeme;Vzero-(dmz.*q-dpz.*q-dmz.*qpz+dpz.*qmz)./(dmz.*dpz.*2.0);Vzero+(dmz.*qzpz-dpz.*qzmz-(dmz.*q-dpz.*q-dmz.*qpz+dpz.*qmz)./(dmz.*2.0)+(dmz.*q-dpz.*q-dmz.*qpz+dpz.*qmz)./(dpz.*2.0))./(dmz.*dpz.*2.0);Vzero+(dmz.*qzzpz-dpz.*qzzmz+(dmz.*qzpz-dpz.*qzmz-(dmz.*q-dpz.*q-dmz.*qpz+dpz.*qmz)./(dmz.*2.0)+(dmz.*q-dpz.*q-dmz.*qpz+dpz.*qmz)./(dpz.*2.0))./(dmz.*2.0)-(dmz.*qzpz-dpz.*qzmz-(dmz.*q-dpz.*q-dmz.*qpz+dpz.*qmz)./(dmz.*2.0)+(dmz.*q-dpz.*q-dmz.*qpz+dpz.*qmz)./(dpz.*2.0))./(dpz.*2.0))./(dmz.*dpz.*2.0);Vzero+qezme./2.0+(dme.*qezeme)./2.0+(dmz.*qepz-dpz.*qemz-dmz.*(qeme+dme.*qeeme)+dpz.*(qeme+dme.*qeeme))./(dmz.*dpz.*4.0);Vzero+(qezme.*(-1.0./2.0)+(dme.*qezeme)./2.0+(dmz.*qepz-dpz.*qemz-dmz.*(qeme+dme.*qeeme)+dpz.*(qeme+dme.*qeeme))./(dmz.*dpz.*4.0))./dme;Vzero+(dmz.*qezpz-dpz.*qezmz-dmz.*(qezme./2.0+(dme.*qezeme)./2.0+(dmz.*qepz-dpz.*qemz-dmz.*(qeme+dme.*qeeme)+dpz.*(qeme+dme.*qeeme))./(dmz.*dpz.*4.0))+dpz.*(qezme./2.0+(dme.*qezeme)./2.0+(dmz.*qepz-dpz.*qemz-dmz.*(qeme+dme.*qeeme)+dpz.*(qeme+dme.*qeeme))./(dmz.*dpz.*4.0)))./(dmz.*dpz.*2.0)];
