function L = Lfun21_(Vzero,dme,dmz,dpe,dpz,q,qeeme,qeme,qemz,qepz,qezeme,qezme,qezmz,qezpz,qme,qmz,qpz,qzmz,qzpz,qzzmz,qzzpz)
%LFUN21_
%    L = LFUN21_(VZERO,DME,DMZ,DPE,DPZ,Q,QEEME,QEME,QEMZ,QEPZ,QEZEME,QEZME,QEZMZ,QEZPZ,QME,QMZ,QPZ,QZMZ,QZPZ,QZZMZ,QZZPZ)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    22-Dec-2020 20:00:55

L = [Vzero+q;Vzero+(q-qme)./dpe;Vzero-(qeme-(q-qme)./dpe)./dpe;Vzero-(qeeme+(qeme-(q-qme)./dpe)./dpe)./dpe;Vzero-(dmz.*q-dpz.*q-dmz.*qpz+dpz.*qmz)./(dmz.*dpz.*2.0);Vzero+(dmz.*qzpz-dpz.*qzmz-(dmz.*q-dpz.*q-dmz.*qpz+dpz.*qmz)./(dmz.*2.0)+(dmz.*q-dpz.*q-dmz.*qpz+dpz.*qmz)./(dpz.*2.0))./(dmz.*dpz.*2.0);Vzero+(dmz.*qzzpz-dpz.*qzzmz+(dmz.*qzpz-dpz.*qzmz-(dmz.*q-dpz.*q-dmz.*qpz+dpz.*qmz)./(dmz.*2.0)+(dmz.*q-dpz.*q-dmz.*qpz+dpz.*qmz)./(dpz.*2.0))./(dmz.*2.0)-(dmz.*qzpz-dpz.*qzmz-(dmz.*q-dpz.*q-dmz.*qpz+dpz.*qmz)./(dmz.*2.0)+(dmz.*q-dpz.*q-dmz.*qpz+dpz.*qmz)./(dpz.*2.0))./(dpz.*2.0))./(dmz.*dpz.*2.0);Vzero+qezme./2.0+(dme.*qezeme)./2.0+(dmz.*qepz-dpz.*qemz-(dmz.*(q-qme))./dpe+(dpz.*(q-qme))./dpe)./(dmz.*dpz.*4.0);Vzero+(qezme.*(-1.0./2.0)+(dme.*qezeme)./2.0+(dmz.*qepz-dpz.*qemz-(dmz.*(q-qme))./dpe+(dpz.*(q-qme))./dpe)./(dmz.*dpz.*4.0))./dme;Vzero-(dmz.*(qezme./2.0+(dme.*qezeme)./2.0+(dmz.*qepz-dpz.*qemz-(dmz.*(q-qme))./dpe+(dpz.*(q-qme))./dpe)./(dmz.*dpz.*4.0))-dpz.*(qezme./2.0+(dme.*qezeme)./2.0+(dmz.*qepz-dpz.*qemz-(dmz.*(q-qme))./dpe+(dpz.*(q-qme))./dpe)./(dmz.*dpz.*4.0))-dmz.*qezpz+dpz.*qezmz)./(dmz.*dpz.*2.0)];
