function L = Lfun33_(Vzero,q)
%LFUN33_
%    L = LFUN33_(VZERO,Q)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    17-Dec-2020 14:01:31

L = [Vzero+q;Vzero;Vzero;Vzero;Vzero;Vzero;Vzero;Vzero;Vzero;Vzero];
