function L = Lfun00_(Vzero,dpe,dpz,q,qeepe,qepe,qezepe,qezpe,qezpz,qezzpz,qpe,qpz,qzpz,qzzpz)
%LFUN00_
%    L = LFUN00_(VZERO,DPE,DPZ,Q,QEEPE,QEPE,QEZEPE,QEZPE,QEZPZ,QEZZPZ,QPE,QPZ,QZPZ,QZZPZ)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    22-Dec-2020 20:00:46

L = [Vzero+q;Vzero-(q-qpe)./dpe;Vzero+(qepe+(q-qpe)./dpe)./dpe;Vzero+(qeepe-(qepe+(q-qpe)./dpe)./dpe)./dpe;Vzero-(q-qpz)./dpe;Vzero+(qzpz+(q-qpz)./dpe)./dpe;Vzero+(qzzpz-(qzpz+(q-qpz)./dpe)./dpe)./dpe;Vzero+qezpe./2.0+qezpz./2.0-(dpe.*qezepe)./2.0-(dpz.*qezzpz)./2.0;Vzero+(qezpe./2.0-qezpz./2.0+(dpe.*qezepe)./2.0+(dpz.*qezzpz)./2.0)./dpe;Vzero+(qezpe.*(-1.0./2.0)+qezpz./2.0+(dpe.*qezepe)./2.0+(dpz.*qezzpz)./2.0)./dpz];
