function L = Lfun10_(Vzero,dme,dpe,dpz,q,qeeme,qeepe,qeme,qepe,qezme,qezpe,qezpz,qezzpz,qme,qpe,qzme,qzpe,qzzpz,qzzzpz)
%LFUN10_
%    L = LFUN10_(VZERO,DME,DPE,DPZ,Q,QEEME,QEEPE,QEME,QEPE,QEZME,QEZPE,QEZPZ,QEZZPZ,QME,QPE,QZME,QZPE,QZZPZ,QZZZPZ)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    22-Dec-2020 21:00:25

L = [Vzero+q;Vzero-(dme.*q-dpe.*q-dme.*qpe+dpe.*qme)./(dme.*dpe.*2.0);Vzero+(dme.*qepe-dpe.*qeme-(dme.*q-dpe.*q-dme.*qpe+dpe.*qme)./(dme.*2.0)+(dme.*q-dpe.*q-dme.*qpe+dpe.*qme)./(dpe.*2.0))./(dme.*dpe.*2.0);Vzero+(dme.*qeepe-dpe.*qeeme+(dme.*qepe-dpe.*qeme-(dme.*q-dpe.*q-dme.*qpe+dpe.*qme)./(dme.*2.0)+(dme.*q-dpe.*q-dme.*qpe+dpe.*qme)./(dpe.*2.0))./(dme.*2.0)-(dme.*qepe-dpe.*qeme-(dme.*q-dpe.*q-dme.*qpe+dpe.*qme)./(dme.*2.0)+(dme.*q-dpe.*q-dme.*qpe+dpe.*qme)./(dpe.*2.0))./(dpe.*2.0))./(dme.*dpe.*2.0);Vzero;Vzero+qzzpz-dpz.*qzzzpz;Vzero+qzzzpz;Vzero+qezpz./2.0-(dpz.*qezzpz)./2.0+(dme.*qzpe-dpe.*qzme)./(dme.*dpe.*4.0);Vzero+(dme.*qezpe-dpe.*qezme-dme.*(qezpz./2.0-(dpz.*qezzpz)./2.0+(dme.*qzpe-dpe.*qzme)./(dme.*dpe.*4.0))+dpe.*(qezpz./2.0-(dpz.*qezzpz)./2.0+(dme.*qzpe-dpe.*qzme)./(dme.*dpe.*4.0)))./(dme.*dpe.*2.0);Vzero+(qezpz./2.0+(dpz.*qezzpz)./2.0-(dme.*qzpe-dpe.*qzme)./(dme.*dpe.*4.0))./dpz];
