function L = Lfun00_(Vzero,dpe,dpz,q,qeeepe,qeepe,qepe,qezepe,qezpe,qezpz,qezzpz,qzpz,qzzpz,qzzzpz)
%LFUN00_
%    L = LFUN00_(VZERO,DPE,DPZ,Q,QEEEPE,QEEPE,QEPE,QEZEPE,QEZPE,QEZPZ,QEZZPZ,QZPZ,QZZPZ,QZZZPZ)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    22-Dec-2020 16:57:16

L = [Vzero+q;Vzero+qepe-dpe.*qeepe;Vzero+qeepe-dpe.*qeeepe;Vzero+qeeepe;Vzero+qzpz-dpz.*qzzpz;Vzero+qzzpz-dpz.*qzzzpz;Vzero+qzzzpz;Vzero+qezpe./2.0+qezpz./2.0-(dpe.*qezepe)./2.0-(dpz.*qezzpz)./2.0;Vzero+(qezpe./2.0-qezpz./2.0+(dpe.*qezepe)./2.0+(dpz.*qezzpz)./2.0)./dpe;Vzero+(qezpe.*(-1.0./2.0)+qezpz./2.0+(dpe.*qezepe)./2.0+(dpz.*qezzpz)./2.0)./dpz];
