function L = Lfun01_(Vzero,dmz,dpe,dpz,q,qeeepe,qeepe,qemz,qepe,qepz,qezepe,qezmz,qezpe,qezpz,qmz,qpz,qzmz,qzpz,qzzmz,qzzpz)
%LFUN01_
%    L = LFUN01_(VZERO,DMZ,DPE,DPZ,Q,QEEEPE,QEEPE,QEMZ,QEPE,QEPZ,QEZEPE,QEZMZ,QEZPE,QEZPZ,QMZ,QPZ,QZMZ,QZPZ,QZZMZ,QZZPZ)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    22-Dec-2020 16:57:17

L = [Vzero+q;Vzero+qepe-dpe.*qeepe;Vzero+qeepe-dpe.*qeeepe;Vzero+qeeepe;Vzero-(dmz.*q-dpz.*q-dmz.*qpz+dpz.*qmz)./(dmz.*dpz.*2.0);Vzero+(dmz.*qzpz-dpz.*qzmz-(dmz.*q-dpz.*q-dmz.*qpz+dpz.*qmz)./(dmz.*2.0)+(dmz.*q-dpz.*q-dmz.*qpz+dpz.*qmz)./(dpz.*2.0))./(dmz.*dpz.*2.0);Vzero+(dmz.*qzzpz-dpz.*qzzmz+(dmz.*qzpz-dpz.*qzmz-(dmz.*q-dpz.*q-dmz.*qpz+dpz.*qmz)./(dmz.*2.0)+(dmz.*q-dpz.*q-dmz.*qpz+dpz.*qmz)./(dpz.*2.0))./(dmz.*2.0)-(dmz.*qzpz-dpz.*qzmz-(dmz.*q-dpz.*q-dmz.*qpz+dpz.*qmz)./(dmz.*2.0)+(dmz.*q-dpz.*q-dmz.*qpz+dpz.*qmz)./(dpz.*2.0))./(dpz.*2.0))./(dmz.*dpz.*2.0);Vzero+qezpe./2.0-(dpe.*qezepe)./2.0+(dmz.*qepz-dpz.*qemz-dmz.*(qepe-dpe.*qeepe)+dpz.*(qepe-dpe.*qeepe))./(dmz.*dpz.*4.0);Vzero+(qezpe./2.0+(dpe.*qezepe)./2.0-(dmz.*qepz-dpz.*qemz-dmz.*(qepe-dpe.*qeepe)+dpz.*(qepe-dpe.*qeepe))./(dmz.*dpz.*4.0))./dpe;Vzero+(dmz.*qezpz-dpz.*qezmz-dmz.*(qezpe./2.0-(dpe.*qezepe)./2.0+(dmz.*qepz-dpz.*qemz-dmz.*(qepe-dpe.*qeepe)+dpz.*(qepe-dpe.*qeepe))./(dmz.*dpz.*4.0))+dpz.*(qezpe./2.0-(dpe.*qezepe)./2.0+(dmz.*qepz-dpz.*qemz-dmz.*(qepe-dpe.*qeepe)+dpz.*(qepe-dpe.*qeepe))./(dmz.*dpz.*4.0)))./(dmz.*dpz.*2.0)];
