function L = Lfun02_(Vzero,dmz,dpe,dpz,q,qeepe,qepe,qezepe,qezmz,qezpe,qezzmz,qmz,qpe,qzmz,qzzmz)
%LFUN02_
%    L = LFUN02_(VZERO,DMZ,DPE,DPZ,Q,QEEPE,QEPE,QEZEPE,QEZMZ,QEZPE,QEZZMZ,QMZ,QPE,QZMZ,QZZMZ)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    22-Dec-2020 20:00:48

L = [Vzero+q;Vzero-(q-qpe)./dpe;Vzero+(qepe+(q-qpe)./dpe)./dpe;Vzero+(qeepe-(qepe+(q-qpe)./dpe)./dpe)./dpe;Vzero+(q-qmz)./dpz;Vzero-(qzmz-(q-qmz)./dpz)./dpz;Vzero-(qzzmz+(qzmz-(q-qmz)./dpz)./dpz)./dpz;Vzero+qezpe./2.0+qezmz./2.0+(dmz.*qezzmz)./2.0-(dpe.*qezepe)./2.0;Vzero+(qezpe./2.0-qezmz./2.0-(dmz.*qezzmz)./2.0+(dpe.*qezepe)./2.0)./dpe;Vzero+(qezpe./2.0-qezmz./2.0+(dmz.*qezzmz)./2.0-(dpe.*qezepe)./2.0)./dmz];
