function L = Lfun22_(Vzero,dme,dmz,dpe,dpz,q,qeeme,qeme,qezeme,qezme,qezmz,qezzmz,qme,qmz,qzmz,qzzmz)
%LFUN22_
%    L = LFUN22_(VZERO,DME,DMZ,DPE,DPZ,Q,QEEME,QEME,QEZEME,QEZME,QEZMZ,QEZZMZ,QME,QMZ,QZMZ,QZZMZ)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    22-Dec-2020 20:00:57

L = [Vzero+q;Vzero+(q-qme)./dpe;Vzero-(qeme-(q-qme)./dpe)./dpe;Vzero-(qeeme+(qeme-(q-qme)./dpe)./dpe)./dpe;Vzero+(q-qmz)./dpz;Vzero-(qzmz-(q-qmz)./dpz)./dpz;Vzero-(qzzmz+(qzmz-(q-qmz)./dpz)./dpz)./dpz;Vzero+qezme./2.0+qezmz./2.0+(dme.*qezeme)./2.0+(dmz.*qezzmz)./2.0;Vzero+(qezme.*(-1.0./2.0)+qezmz./2.0+(dme.*qezeme)./2.0+(dmz.*qezzmz)./2.0)./dme;Vzero+(qezme./2.0-qezmz./2.0+(dme.*qezeme)./2.0+(dmz.*qezzmz)./2.0)./dmz];
