function L = Lfun33_(Vzero,q)
%LFUN33_
%    L = LFUN33_(VZERO,Q)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    22-Dec-2020 20:00:58

L = [Vzero+q;Vzero;Vzero;Vzero;Vzero;Vzero;Vzero;Vzero;Vzero;Vzero];
