state  = {'e','z'};
dvec   = {'dme','dmz','dpe','dpz','dae','daz'};
value  = {'vi','vei','vzi','vh','veh','vzh'};

vars   = {'q','psii','mue','sigqk','sigqs'};

vars_  = {'qe', 'qee', ...
          'qz', 'qzz', ...
          'qez','qeze','qezz'...
          'wi','wh','ci','ch',...
          'sigma','siges','sigek',...
          'muri','murh',...
          'muk','muq','r',...
          'muni','munh','signis','signhs','signik','signhk',...
          'sigxis','sigxhs','sigxik','sigxhk','iotai','iotah','muz',...
          'sigV11','sigV22','sigV12','muV1','muV2','uVi','uVh','rVi','rVh'}; 
      
vplot_ = {'vi'};

last   = {'q',...
          'qe', 'qee', 'qeee',...
          'qz', 'qzz', 'qzzz',...
          'qez','qeze','qezz'};

latex_ = {'$q_\eta$','$q_{\overline{\eta}}$','$q_{\eta\eta}$','$q_{\overline{\eta}\overline{\eta}}$',...
          '$q_{{\eta}\overline{\eta}}$','$q_{\eta\overline{\eta}\eta}$','$q_{\eta\overline{\eta}\overline{\eta}}$',...
          '$q_\eta$','$q_{\overline{\eta}}$','$q_{\eta\eta}$','$q_{\overline{\eta}\overline{\eta}}$',...
          '$q_{{\eta}\overline{\eta}}$','$q_{\eta\overline{\eta}\eta}$','$q_{\eta\overline{\eta}\overline{\eta}}$'...
          'phii','phih',...
          'wi','wh','ci','ch',...
          'sigma','siges','sigek',...
          'muri','murh',...
          'muk','muq','r',...
          'muni','munh','signis','signhs','signik','signhk',...
          '$\sigma^{\xi}$','$\sigma^{\xi}$','$sigxik$','$sigxhk$','$\iota^i$','$\iota^h$','$\mu^z$'};

latex  = {'$q$','$\psi$','$mue$','$sigqk$','$sigqs$'};

latexv = {'$v^i$','$v_\eta^i$','$v_z^i$','$v^h$','$v_\eta^h$','$v_z^h$'};

