function L = Lfun33_(Vzero,q)
%LFUN33_
%    L = LFUN33_(VZERO,Q)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    16-Nov-2020 16:53:51

L = [Vzero+q;Vzero;Vzero;Vzero;Vzero;Vzero;Vzero;Vzero;Vzero;Vzero];
