function CC = CCfun33_(aa,ab,e,gammai,mua,mub,qa,qb,siga,sigb,sigea,sigeb,vei,vi,vzi,wi,wia,z)
%CCFUN33_
%    CC = CCFUN33_(AA,AB,E,GAMMAI,MUA,MUB,QA,QB,SIGA,SIGB,SIGEA,SIGEB,VEI,VI,VZI,WI,WIA,Z)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    12-Jul-2020 01:22:13

CC = (gammai.*siga.^2.*wi.^2+gammai.*sigb.^2.*wi.^2).*(-wi.*(mua-mub+aa./qa-ab./qb)+siga.*((e.*sigea.*vei)./vi-(siga.*vzi.*z.*(z-1.0))./vi).*(gammai-1.0)-sigb.*((e.*sigeb.*vei)./vi+(sigb.*vzi.*z.*(z-1.0))./vi).*(gammai-1.0)+gammai.*sigb.^2.*wi.^2.*(wia-1.0)+gammai.*siga.^2.*wi.^2.*wia);
