
state  = {'e','z'};
dvec   = {'dme','dmz','dpe','dpz','dae','daz'};
value  = {'vi','vei','vzi','vh','veh','vzh'};
vars   = {'q','mue','sigw', 'sigx','theta'};
prices = {'q'};

% all secondary variables are put in vars_ MATLAB variable; these secondary variables are computed from
% the endogenous variables in vars; the mapping is given in the paper and
% in writefun.m
vars_  = {'qe', 'qee', ...
          'qz', 'qzz', ...
          'qez','qeze','qezz',...
          'ci','ch',...
          'sigz_',...
          'muq','r',...
          'muni','munh','sign',...
          'sigxii','sigxih','g','muz', ...
          'pii', 'iotai', 'v', 'x', 'k', 'sigq',...
          'sigV11','sigV22','sigV12','muV1','muV2','uVi','uVh','rVi','rVh'};

vplot_ = {'vi'};

% these are the latex symbols used for graphs
latex  = {'$q$','$\mu^{\eta}$','$\sigma^w$','$\sigma^x$','$\theta$'};

latex_ ={'$q_\eta$','$q_{\overline{\eta}}$','$q_{\eta\eta}$','$q_{\overline{\eta}\overline{\eta}}$',...
          '$q_{{\eta}\overline{\eta}}$','$q_{\eta\overline{\eta}\eta}$','$q_{\eta\overline{\eta}\overline{\eta}}$',...
          '$q_\eta$','$q_{\overline{\eta}}$','$q_{\eta\eta}$','$q_{\overline{\eta}\overline{\eta}}$',...
          '$q_{{\eta}\overline{\eta}}$','$q_{\eta\overline{\eta}\eta}$','$q_{\eta\overline{\eta}\overline{\eta}}$',...
          'ci','ch',...
          'sigma','sigz_',...
          'muq','r',...
          'muni','munh','sign',...
          'sigxii','sigxih','g','muz', ...
          'pii', 'iotai', 'v', 'x', 'k', 'sigq'};

latexv = {'$v^i$','$v_\eta^i$','$v_z^i$','$v^h$','$v_\eta^h$','$v_z^h$'};

